server:
  shutdown: graceful
  port: 8903
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true
sparkzxl:
  injection:
    enabled: true
    aop-enabled: true
knife4j:
  enable: true
  documents:
    -
      group: 1.2.x
      name: 测试自定义标题分组
      locations: classpath:md/*
  setting:
    enableSwaggerModels: true
    enableDocumentManage: true
    enableHost: false
    enableRequestCache: true
    enableFilterMultipartApis: false
    enableFilterMultipartApiMethodType: POST
    language: zh-CN
  cors: false
  production: false
  group-name: test测试应用
  base-package: com.sparksys.test.interfaces
  title: activiti工作流应用
  description: test测试管理
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  licenseUrl: https://github.com/sparkzxl
  contact:
    url: https://github.com/sparkzxl
    name: zhouxinlei
    email: zhouxinlei298@163.com
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.sparksys.test.infrastructure.entity
  type-enums-package: com.sparksys.test.infrastructure.enums
  mapper-scan: com.sparksys.test.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  application:
    name: sparksys-test-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 5d664600-38cc-4862-bf65-d1e24ca6ce59
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-bp1cp68o8t1gq604p5o.mysql.rds.aliyuncs.com/sparksys_authorization?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: zhouxinlei
    password: zxl298828
  redis:
    host: 47.114.40.129
    port: 6379
    time-out: 28800
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: 200
        min-idle: 0
dubbo:
  # Dubbo 服务注册中心配置，对应 RegistryConfig 类
  registry:
    address: spring-cloud://127.0.0.1:8848 # 指定 Dubbo 服务注册中心的地址
  # Spring Cloud Alibaba Dubbo 专属配置项，对应 DubboCloudProperties 类
  cloud:
    subscribed-services: sparksys-authority-server
